{{- if .Values.scraper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scraper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "scraper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.scraper.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scraper.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with include "scraper.strategy" . }}
  strategy:
    {{- trim . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scraper.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.scraper.labels.pods }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.scraper.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.scraper.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.scraper.image.repository }}:{{ .Values.scraper.image.tag }}"
          imagePullPolicy: {{ .Values.scraper.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.scraper.service.port }}
              protocol: TCP
          {{- with .Values.scraper.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.scraper.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scraper.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scraper.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
