apiVersion: v1
kind: Service
metadata:
  name: {{ include "scraper.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "scraper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.scraper.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.scraper.service.type }}
  ports:
    - port: {{ .Values.scraper.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "scraper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
