apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pricebuddy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pricebuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.pricebuddy.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pricebuddy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.pricebuddy.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pricebuddy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.pricebuddy.labels }}
        {{- with .Values.pricebuddy.labels.pods }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      {{- with .Values.pricebuddy.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.pricebuddy.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.pricebuddy.image.repository }}:{{ .Values.pricebuddy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pricebuddy.image.pullPolicy }}
          env:
            - name: APP_URL
              value: {{ .Values.pricebuddy.appUrl | quote }}
            - name: ASSET_URL
              value: {{ .Values.pricebuddy.appUrl | quote }}
            - name: SCRAPER_BASE_URL
              value: {{ .Values.pricebuddy.scraperBaseUrl | quote }}
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_DATABASE
              value: {{ .Values.pricebuddy.postgresql.database | quote }}
            - name: DB_USERNAME
              value: {{ .Values.pricebuddy.postgresql.user | quote }}
            - name: DB_PORT
              value: {{ .Values.pricebuddy.postgresql.port | quote }}
            - name: DB_HOST
              value: {{ .Values.pricebuddy.postgresql.host | quote }}
            {{- if .Values.pricebuddy.existingSecret }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pricebuddy.secret-name" . }}
                  key: db_password
                  optional: true
            {{- end }}
            {{- if .Values.pricebuddy.existingSecret }}
            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pricebuddy.secret-name" . }}
                  key: app_user_password
                  optional: true
            {{- end }}
            {{- with .Values.pricebuddy.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.pricebuddy.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- with .Values.pricebuddy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-storage-volume
              mountPath: /app/storage
      volumes:
        - name: {{ .Release.Name }}-storage-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pricebuddy.persistence.existingClaim | default (printf "%s-storage" (include "pricebuddy.fullname" .)) }}
      {{- with .Values.pricebuddy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pricebuddy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pricebuddy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pricebuddy.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range . }}
        - {{- if not .labelSelector }}
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "pricebuddy.name" $ }}
              app.kubernetes.io/instance: {{ $.Release.Name }}
          {{- end }}
          {{- toYaml . | nindent 10 | trim }}
        {{- end }}
      {{- end }}

